# Change these first
owner: climateseed # Your GitHub organization or username, where this repository lives
repo: services-health # GitHub repository name
status-website:
  baseUrl: /services-health
  
  logoUrl: https://raw.githubusercontent.com/ClimateSeed/services-health/master/assets/c_green.png
  name: Climatseed services status
  introTitle: "Here you can find uptime of different climateseed's services"
  navbar:
    - title: Status
      href: /

sites:
  - name: Gems (Website)
    url: https://gems.climateseed.com
  - name: Gems (API)
    url: https://dev.gems.climateseed.com/api/k8/liveness
  - name: Gold (Website)
    url: https://app.climateseed.com
assignees:
  - asyade
