# Change these first
owner: climateseed # Your GitHub organization or username, where this repository lives
repo: services-health # GitHub repository name
status-website:
  baseUrl: /services-health
  
  logoUrl: https://raw.githubusercontent.com/ClimateSeed/services-health/master/assets/c_green.png
  name: ClimatSeed's Services Systems Status
  navbar:
    - title: Status
      href: https://climateseed.com

sites:
  - name: GEMS (Website)
    url: https://gems.climateseed.com
  - name: GEMS (API)
    url: https://dev.gems.climateseed.com/api/k8/liveness
  - name: Contribution Platform (Website)
    url: https://app.climateseed.com
assignees:
  - reemalsobaiee-cs
  - Aeradriel
